# Ejercicio día 8
**Programación I**  
**María Fernanda López Ortega**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [97]:
import numpy as np #se importa Numpy

In [346]:
fila = int(input("Ingrese número de fila: "))  #Se ingresa las filas máximas
columna = int(input("Ingrese número de columnas: "))  # Se ingresa las columnas máximas
A = np.zeros(fila*columna)   #se crea una lista con ceros
v = int(fila*columna/2)  #se calcula la mitad de los elementos
A[:v] = 1  #la mitad de los elementos se les coloca el el valor de 1
np.random.shuffle(A)  #se reordenan los elementos de una forma aleatoria
print(A.reshape(fila,columna))  #se crea la matriz

Ingrese número de fila: 20
Ingrese número de columnas: 20
[[1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1

In [355]:
type(A)

numpy.ndarray

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



### Inciso A

In [26]:
Ceros = np.zeros([5,2], dtype=int) #matriz de ceros
Unos = np.ones([5,2], dtype=int) #matriz de unos

In [44]:
a= Ceros.flatten() #se convierte en una sola lista la matriz
a2=a[:, None] #se convierte en vector columna
print(a2)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [45]:
b = Unos.flatten() #se convierte en una sola lista la matriz
b2= b[:, None] #se convierte en vector colunma
print(b2)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


### Inciso B

In [48]:
terceraDimension = np.dstack((a2,b2)) #se crea la tercera dimensión
print(terceraDimension)

[[[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[0 1]]]


### Inciso C

In [60]:
Ceros = np.zeros([5,2], dtype=int) #matriz de ceros
Unos = np.ones([5,2], dtype=int) #matriz de unos

In [54]:
a= Ceros.flatten() #se convierte en una lista la matriz
a2=a[:, None] 
b = Unos.flatten() 
b2= b[:, None]


In [68]:
fila = np.concatenate((a2, b2), axis=0) #se concatena verticalmente
print(fila)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una matriz. 

In [64]:
def f(matriz):
    return 2* matriz[:,0] + 3*matriz[:,1] + matriz[:,2]**2 #se coloca la posicion de cada columna indicando a x,y y z 

In [66]:
fila = int(input("Ingrese número de filas: ")) #se ingresa el número máx. de filas, ya que las columnas son fijas. 
matriz = np.floor(10*np.random.random((fila,3))) #se crean valores aleatorios para cada variable
matriz

print(f(matriz)[:, None]) #se llama a la función para realizar la operación correspondiente. 


Ingrese número de filas: 5
[[116.]
 [ 29.]
 [ 27.]
 [ 33.]
 [ 18.]]


## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [456]:
#valores= np.floor(50*np.random.random((100,2)))
fila = 50 #lado del cuadrado
columna = 50 #lado del cuadrado
matriz0 = np.floor(2*np.random.random([fila,columna])) #se crea una matriz con 0 y 1 aleatorios
matriz = matriz0.astype(np.int32) #los valores se pasan de flotantes a enteros
totalPuntos = np.sum(matriz) #se suman todos los unos del cuadrado grande
pequeña=matriz[15:35, 15:35] #se acota la matriz para obtener el cuadrado pequeño
puntosAdentro = np.sum(pequeña) #se suman los unos de esa area
AreaPequeña = fila*columna*(puntosAdentro/totalPuntos) #calculo del area del cuadrado pequeño
AreaPequeña

399.0422984836393

## Ejercicio 5

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

### 1 FormString
Crea una lista a partir de una cadena, se le define cual es el separador entre numeros

In [3]:
print(np.fromstring('4 6 7', dtype=int, sep=' '))
print(np.fromstring('8,4,6', dtype=int, sep=','))

[4 6 7]
[8 4 6]


## 2 tri
Crea una matriz de los valores especificado nxm, si no se define m se usara N.
K indica en donde se realiza la diagonal, agrega 0s debajo de la linea indicada(K)

In [4]:
np.tri(3, 5, 3)

array([[1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 3 MAT
Crea una matriz a partir de una secuencia, arreglo o una cadena

In [5]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

np.bmat([[A, B], [C, D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

### 4 arange

Crea un arreglo  a partir de un numero de inicio y un final, se recorre de uno en uno a menos 
que se defina un intervalo

In [6]:
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,16,2))

[0 1 2]
[3 4 5 6]
[ 3  5  7  9 11 13 15]


### 5 Empty
Crea un arreglo para el tamaño definido, esta lista no esta inicializada.
Cujenta con valores random

In [7]:
np.empty([1, 3])

array([[1.19732507e-311, 1.19732492e-311, 1.19732507e-311]])

### 6 Identity
Crea una lista que representa una matriz identidad

In [9]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 7 Copy
Crea una copia de una matriz, como el metodo "deepcopy", ya que si no es una
variable por referencia y no por valor

In [10]:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
print(x)
print(y)
print(z)
print("Asignaciones: ")
x[1] = 10
z[0] = 8

print(x)
print(y)
print(z)

[1 2 3]
[1 2 3]
[1 2 3]
Asignaciones: 
[ 1 10  3]
[ 1 10  3]
[8 2 3]


### 8 loadtxt
Carga datos desde un archivo de texto.
Los datos deben ser consistentes en cuanto a cantidad y formato. 
Se puede definir el limitador de los caracteres

In [11]:
from io import StringIO #simula ser un archivo 
c = StringIO(u"2 1\n2 3")
print(np.loadtxt(c))

[[2. 1.]
 [2. 3.]]


### 9 FromFunction
Construye un arreglo ejecutando una funcion sobre coordenadas

In [12]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 10 linspace

Devuelve números espaciados uniformemente en un intervalo especificado.

In [13]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

### 11 fromfile
Crea un arreglo a partir de texto o un archivo binario

In [14]:
import os
import tempfile
#creation of file array
dt = np.dtype([('time', [('min', int), ('sec', int)]), ('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10; x['temp'] = 98.25

fname = tempfile.mkstemp()[1]
x.tofile(fname)
#The recommended way to store and load data:
np.save(fname, x)
np.load(fname + '.npy')

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i4'), ('sec', '<i4')]), ('temp', '<f8')])

### 12 bitwise_and
Calcula el AND bit a bit de la representación binaria de los entereos en las matrices de entrada.

In [4]:
A =[1, 2, 3, 4]
B = [9, 8, 7, 5]

prueba = np.bitwise_and(A,B)
print(prueba)

[1 0 3 4]


### 13 bitwise_or
Calcula el OR bit a bit de la representación binaria de los entereos en las matrices de entrada.

In [462]:
prueba = np.bitwise_or(A,B)
print(prueba)

[ 9 10  7  5]


###  14 bitwise_xor
Calcula el XOR bit a bit de la representación binaria de los entereos en las matrices de entrada.

In [7]:
prueba = np.bitwise_xor(A,B)
print(prueba)

[ 8 10  4  1]


### 15 invert
Calcula la inversión a nivel de bit, o NO a nivel de bit, a nivel de elemento.

In [9]:
prueba = np.invert(A)
print(prueba)

array([-2, -3, -4, -5], dtype=int32)

### 16 left_shift  
Desplaza los bits de un entero a la izquierda.

In [11]:
prueba = np.left_shift(A,B)
print(prueba)

[512 512 384 128]


### 17 right_shift
Desplaza los bits de un entero a la derecha.

In [12]:
prueba = np.right_shift(A,B)
print(prueba)

[0 0 0 0]


### 18 packbits 
Empaqueta los elementos de una matriz con valores binarios en bits en una matriz uint8.

In [19]:
A = [[1,2],[3,2],[8,7]]
prueba = np.packbits(A,axis = -1)
print(prueba)

[[192]
 [192]
 [192]]


### 19 unpackbits
Desempaqueta elementos de una matriz uint8 en una matriz de salida con valores binarios.

In [47]:
A = np.array([[3,9],[2,3],[8,9]], dtype = np.uint8)
prueba = np.unpackbits(A)
print(prueba)

[0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1
 0 0 0 0 0 0 0 1 0 0 1]


### 20 binary_repr
Devuelve la representación binaria del número de entrada como una cadena.

In [48]:
prueba = np.binary_repr(-9)
print(prueba)

-1001


### 21 array2string 
Devuelve una representación de cadena de una matriz.

In [49]:
x  = np.arange(3)
np.array2string(x, formatter={'int':lambda x: hex(x)})


'[0x0 0x1 0x2]'

### 22 array_repr
Devuelve la representación de cadena de una matriz.

In [50]:
np.array_repr(np.array([1,2]))

'array([1, 2])'

### 23 array_str 
Devuelve una representación de cadena de los datos en una matriz.

In [51]:
np.array_str(np.arange(3))

'[0 1 2]'

### 24 format_float_positional 
Formatee un escalar de coma flotante como una cadena decimal en notación posicional.

In [52]:
np.format_float_positional(np.float32(np.pi))

'3.1415927'

### 25 format_float_scientific
Formatee un escalar de coma flotante como una cadena decimal en notación científica.

In [53]:
np.format_float_scientific(np.float32(np.pi))

'3.1415927e+00'

### 26 set_printoptions  
Establecer opciones de impresión.

In [60]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

### 27 get_printoptions
Devuelve las opciones de impresión actuales.

In [61]:
np.get_printoptions( )

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 4,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

### 28 set_string_function 
Configure una función de Python para usar cuando imprima matrices bonitas.

In [62]:
def pprint(arr):
    return 'HA! - What are you going to do now?'

np.set_string_function(pprint)
a = np.arange(10)
a

HA! - What are you going to do now?

### 29 savetxt
Guarda datos de una lista a un archivo


In [15]:
x = np.arange(0.0,5.0,1.0)
print(x)
np.savetxt('test.txt', x, delimiter=',')

[0. 1. 2. 3. 4.]


### 30 copyto
Copia valores de un array a otro

In [63]:
gfg = np.array([1, 2, 3]) 
geeks = [4, 5, 6] 
np.copyto(gfg, geeks)    
print(gfg) 

[4 5 6]


### 31 shape
Retorna las dimensiones de un arreglo

In [16]:
np.shape(np.eye(3,1))

(3, 1)

### 32 Reshape
Reorganiza un arreglo de n x m, a un a x b

In [17]:
print(np.arange(6))
a = np.arange(6).reshape((3, 2))
print (a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


### 33 Ravel
Lista todos los datos de una matriz. Equivalente a reshape(-1, order=order)

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

### 34 Moveaxis
Mueve los ejes de un arreglo  a una nueva posicion

In [19]:
x = np.zeros((3, 4, 5))
print(np.moveaxis(x, 0, -1).shape)

(4, 5, 3)


### 35 atleast_1d
Convierta entradas en matrices con al menos una dimensión.

In [20]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

### 36 Asarray
Convierte la entrada en un arreglo

In [21]:
a = [1, 2]
np.asarray(a)

array([1, 2])

### 37 Expand dims
Expande la forma de un arreglo

In [22]:
x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
print(y)

[[1 2]]


### 38 squeeze
Eliminar entradas unidimensionales de la forma de una matriz.


In [23]:
x = np.array([[[0], [1], [2]]])
print(x.shape)
print(np.squeeze(x).shape)

(1, 3, 1)
(3,)


### 39 asscalar
Convierte un arreglo de tamaño 1 en un  escalar equivalente

In [24]:
np.asscalar(np.array([24]))

24

### 40 concatenate
Une una sequencia de arreglos a un eje 

In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 41 stack
Une una sequencia de matrices a un eje 

In [26]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

### 42 split
Divide un array en multiples su arreglos

In [27]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

### 43 block
Arma un arrelgo de varias dimensiones de una lista anidadas de bloques

In [28]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

### 44 tile
Contruye un arreglo repitiendo un numero de veces un arreglo dado

In [29]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

### 45 repeat
Repite elementos de un arreglo

In [30]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)


array([1, 1, 2, 2, 3, 3, 4, 4])

### 46 delete
Retorna un nuevo arreglo con sub arreglos a lo largo de un eje eliminado

In [31]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print(np.delete(arr, 1, 0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


### 47 insert
Inserta valores a lo largo de un eje  antes de dar los indices 

In [32]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(np.insert(a, 1, 5))

[1 5 1 2 2 3 3]


### 48 resize
retorna un arreglo de dimensiones especificadas

In [33]:
a=np.array([[0,1],[2,3]])
print(a)
print(np.resize(a,(2,3)))

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 1]]


### 49 unique
Encuentra elementos unicos en un arreglo

In [34]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

### 50 flip
Revierte el orden de un arreglo de arreglos en un eje dado

In [35]:
A = np.arange(8).reshape((2,2,2))
print(A)
print(np.flip(A, 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


### 51 roll
Invierte los valores en un arreglo 

In [36]:
x = np.arange(10)
print( np.roll(x, 2))

[8 9 0 1 2 3 4 5 6 7]


### 52 Tril 
Devuelve una copia de una matriz con elementos por encima de la diagonal k con valores iguales a cero

In [37]:
np.tril([[2,2,8],[3,5,6],[4,4,1]], 0)

array([[2, 0, 0],
       [3, 5, 0],
       [4, 4, 1]])

### 53 Vsplit

Dividir una matriz en varias submatrices verticalmente (en cuanto a fila)


In [38]:
x = np.arange(16.0).reshape(4, 4)
print(x)
np.vsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

### 54 Diag

Extraer una diagonal o construir una matriz diagonal

In [39]:
x=np.arange(4).reshape(2,2)
print (x)
np.diag(x)

[[0 1]
 [2 3]]


array([0, 3])

### 55 Logspace 

Números de retorno espaciados uniformemente en escala logarítmica de registro

In [40]:
np.logspace(3.0, 5.0, num=4)

array([  1000.        ,   4641.58883361,  21544.34690032, 100000.        ])

### 56 Append

Anexar valores al final de una matriz

In [41]:
np.append([2, 8], [[4, 5, 6], [7, 8, 9]])

array([2, 8, 4, 5, 6, 7, 8, 9])

### 57 Rot90

Gire una matriz 90 grados en el plano especificado por los ejes.

In [42]:
m = np.array([[2,8],[4,9]], int)
print(m)
np.rot90(m)

[[2 8]
 [4 9]]


array([[8, 9],
       [2, 4]])

### 58 Rot90

Gire una matriz 90 grados en el plano especificado por los ejes.

In [43]:
x = np.array([2, 4])
print(x.shape)
y = np.expand_dims(x, axis=0)
print(y)
print(y.shape)

(2,)
[[2 4]]
(1, 2)


### 59 DSplit

Dividir matriz en varias submatrices a lo largo del 3er eje

In [47]:
x = np.arange(16.0).reshape(2, 2, 4)
x
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

### 60 HSplit

Dividir una matriz en varias submatrices horizontalmente (en cuanto a columnas)

In [48]:
x = np.arange(16.0).reshape(4, 4)
print(x)

np.hsplit(x, 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

### 61 Swapaxes

Intercambia dos ejes de una matriz

In [50]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

### 62 full
Devuelve un nuevo conjunto de formas y tipos dados, rellenos con fill_value .

In [64]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

### 63 ones
Devuelve un nuevo conjunto de formas y tipos dados, rellenos con unos.

In [65]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

### 64 ones_like
Devuelve una matriz de unidades con la misma forma y tipo que una matriz determinada.

In [66]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

### 65 zeros
Devuelve una nueva matriz de formas y tipos dados, llenos de ceros.

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 66 zeros_like
Devuelve una matriz de ceros con la misma forma y tipo que una matriz determinada.

In [68]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

### 67 full_like
Devuelve una matriz completa con la misma forma y tipo que una matriz determinada.

In [69]:
x = np.arange(6, dtype=int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

### 68 frombuffer
Interprete un búfer como una matriz unidimensional.

In [70]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

### 69 vander 
Genera una matriz de Vandermonde.

In [71]:
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

### 70 geomspace 
Números de retorno espaciados uniformemente en una escala logarítmica (una progresión geométrica).

In [72]:
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])

### 71 diagflat
Cree una matriz bidimensional con la entrada aplanada como una diagonal.

In [73]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 72 broadcast 
Produzca un objeto que imite la transmisión.

In [77]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### 73 upper
Devuelve una matriz con los elementos convertidos a mayúsculas.

In [80]:
c = np.array(['a1b c', '1bca', 'bca1']); 
np.char.upper(c)

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

## 2 Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

In [88]:
import numpy as np
x = np.random.random((5,5))
y = np.arange(2,7,6)

np.savez('prueba.bin', objX = x, objY = y)

In [89]:
j=np.load('prueba.bin.npz')

In [90]:
j['objX']

array([[0.39431227, 0.36875636, 0.78522611, 0.95357356, 0.50155335],
       [0.62682323, 0.57371649, 0.22908936, 0.30335949, 0.58807401],
       [0.79427794, 0.78581852, 0.26861782, 0.34562707, 0.91398345],
       [0.60132112, 0.9712588 , 0.60733412, 0.79897056, 0.10815276],
       [0.77697178, 0.12520549, 0.54117315, 0.82371347, 0.33578972]])

In [91]:
j['objY']

array([2])

## 3 Ejemplo cargar y guardar txt

In [82]:
import numpy as np
from io import StringIO

##cargar archivo
file = open("prueba.txt", "r")
print(np.loadtxt(file, delimiter=' '))

## guardar archivo
x = y = z = np.arange(0.0,5.0,1.0)
np.savetxt('prueba2.txt', x, delimiter=',')

[0. 1. 2. 3. 4.]


## 4 Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 

In [106]:
def EstimacionMCO():
    Archivo= str(input("Ingrese nombre del archivo: "))
    dato = np.genfromtxt(Archivo,delimiter=',')
    X=dato[:,0:6]
    Y=dato[:,6:7]
    A=(X.T)@X
    B=(X.T)@Y
    Beta=((np.linalg.inv(A))@B)
    return Beta

In [113]:
EstimacionMCO()

Ingrese nombre del archivo: Libro1.csv


array([[ 2.01210707],
       [-0.77640954],
       [-0.22507767],
       [-0.64495051],
       [-0.19022252],
       [-0.15355665]])